Vagrant.configure("2") do |config|
  
 
	config.vm.box = "ubuntu/bionic64"

  
	config.vm.network :forwarded_port, guest: 4080, host: 8080 #confluence port
	config.vm.network :forwarded_port, guest: 3306, host: 3306 #DB port
	#config.vm.synced_folder "D:/053/hometask_3", "/home/vagrant/"
	config.vm.provider "virtualbox" do |vb|
  
     vb.memory = "4128"
   end
  
	config.vm.provision "shell", path: "docker.sh"
	config.vm.provision "shell", path: "docker_compose.sh"
end

